name: 🚀 Release

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: Select the version to increment such as major, minor, or patch
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  actions: read

jobs:
  release:
    name: Release Package
    uses: grovegs/workflows/.github/workflows/package-release.yml@v1.3.0
    with:
      package-name: Serialization
      version-type: ${{ inputs.version-type }}
      runs-on: ubuntu-latest
      dotnet-project: src/GroveGames.Serialization
      global-json-file: global.json
      directory-build-props: Directory.Build.props
      readme-file: README.md
      license-file: LICENSE
      godot-addon: src/GroveGames.Serialization.Godot/addons/GroveGames.Serialization
      unity-package: src/GroveGames.Serialization.Unity/Packages/com.grovegames.serialization
      create-tag: true
      publish-github: true
      publish-nuget: true
      publish-discord: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      client-id: ${{ secrets.CLIENT_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
