name: 🧪 Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  tests:
    uses: grovegs/workflows/.github/workflows/package-tests.yml@v1.3.0
    with:
      dotnet-project: tests/GroveGames.Serialization.Tests
      global-json-file: global.json

  generator-tests:
    uses: grovegs/workflows/.github/workflows/package-tests.yml@v1.3.0
    with:
      dotnet-project: tests/GroveGames.Serialization.Generator.Tests
      global-json-file: global.json
